# LoadBalancer Service for Kafka Wireline Proxy -- Instance Load Balancer
############################################################################
# #####   Create one LoadBalancer service per instance / Pod replica   #####
# #####   There should be one CRD per instance in the StatefulSet      #####
############################################################################
# - The loadbalancer host/address should be used to set the EXTERNAL_LB_HOST_LIST
#   environment variable in the StatefulSet definition.
# - The value will be used to resolve 'advertised.listeners' in the Kafka Wireline Proxy StatefulSet configmap.
# - This service will allow clients to connect directly to the instance.
# - The service name will be used as the hostname for the instance
---
# POD-0
apiVersion: v1
kind: Service
metadata:
  name: kafka-wireline-proxy-instance-lb-0
  namespace: kafka-proxy
  annotations:
    # Azure Load Balancer annotations (replacing AWS ELB annotations)
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"  # External load balancer
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "30"
    
    # Health probe configuration (equivalent to AWS health checks)
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "HTTP"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-port: "8080"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/health"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-interval: "30"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe: "2"
    
    # Azure Load Balancer SKU (Standard is recommended for production)
    service.beta.kubernetes.io/azure-load-balancer-mode: "shared"  # or "auto" for Standard SKU
    
    # Optional: Specify resource group for load balancer (if different from cluster RG)
    # service.beta.kubernetes.io/azure-load-balancer-resource-group: "your-lb-resource-group"
    
    # Optional: Static IP allocation for this specific instance (if you have reserved IPs)
    # service.beta.kubernetes.io/azure-load-balancer-ipv4: "your-static-ip-for-pod-0"
    
    # Session affinity disabled for instance-specific connections
    service.beta.kubernetes.io/azure-load-balancer-enable-high-availability-ports: "false"
    
spec:
  type: LoadBalancer
  # Important: Set externalTrafficPolicy to Local
  externalTrafficPolicy: Local
  selector:
    app: kafka-wireline-proxy
    # IMPORTANT: Ensure this matches the pod name for the specific instance/Pod replica
    statefulset.kubernetes.io/pod-name: kafka-wireline-proxy-0    # Targets only the kafka-0 pod
  ports:
    # - Instance-specific ports for direct pod access
    # - For externally facing load balancer, these should be secure ports only
    #   or security policy should be applied to restrict access via NSG
    # - Ports should match to ports in the StatefulSet
    - name: kafka-ssl
      port: 9094
      targetPort: 9094
      protocol: TCP
---
# POD-1
apiVersion: v1
kind: Service
metadata:
  name: kafka-wireline-proxy-instance-lb-1
  namespace: kafka-proxy
  annotations:
    # Azure Load Balancer annotations (replacing AWS ELB annotations)
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"  # External load balancer
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "30"
    
    # Health probe configuration (equivalent to AWS health checks)
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "HTTP"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-port: "8080"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/health"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-interval: "30"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe: "2"
    
    # Azure Load Balancer SKU (Standard is recommended for production)
    service.beta.kubernetes.io/azure-load-balancer-mode: "shared"  # or "auto" for Standard SKU
    
    # Optional: Specify resource group for load balancer (if different from cluster RG)
    # service.beta.kubernetes.io/azure-load-balancer-resource-group: "your-lb-resource-group"
    
    # Optional: Static IP allocation for this specific instance (if you have reserved IPs)
    # service.beta.kubernetes.io/azure-load-balancer-ipv4: "your-static-ip-for-pod-1"
    
    # Session affinity disabled for instance-specific connections
    service.beta.kubernetes.io/azure-load-balancer-enable-high-availability-ports: "false"
    
spec:
  type: LoadBalancer
  # Important: Set externalTrafficPolicy to Local
  externalTrafficPolicy: Local
  selector:
    app: kafka-wireline-proxy
    # IMPORTANT: Ensure this matches the pod name for the specific instance/Pod replica
    statefulset.kubernetes.io/pod-name: kafka-wireline-proxy-1    # Targets only the kafka-1 pod
  ports:
    # - Instance-specific ports for direct pod access
    # - For externally facing load balancer, these should be secure ports only
    #   or security policy should be applied to restrict access via NSG
    # - Ports should match to ports in the StatefulSet
    - name: kafka-ssl
      port: 9094
      targetPort: 9094
      protocol: TCP
